# Generated by Django 5.1.4 on 2025-01-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_sold',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_total',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
