# Generated by Django 5.1.4 on 2025-01-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0005_alter_actor_image_alter_director_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(null=True, upload_to='D:\\coursi\\venv\\homework\\DjangoProject3\\cinema/media/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to='D:\\coursi\\venv\\homework\\DjangoProject3\\cinema/media/'),
        ),
    ]
