# Generated by Django 5.1.4 on 2025-01-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_alter_actor_image_alter_director_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\coursi\\venv\\homework\\DjangoProject3\\cinema/media/'),
        ),
    ]
