# Generated by Django 5.1.4 on 2025-01-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0007_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(null=True, upload_to='D:\\coursi\\venv\\homework\\DjangoProject3\\DjangoCinemaProject\\cinema/media/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to='D:\\coursi\\venv\\homework\\DjangoProject3\\DjangoCinemaProject\\cinema/media/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\coursi\\venv\\homework\\DjangoProject3\\DjangoCinemaProject\\cinema/media/'),
        ),
    ]
